### ISSUE TITLE
Test Model eos8c0o

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos8c0o#2]
Hi @pauline-banye and @Femme-js !

Please try out this model on Colab and CLI and let us know if it works fine!

**Comment by pauline-banye** [comment]
@GemmaTuron 
### MODEL TEST FOR EOS8C0O

## CLI
- [x]  Model eos8c0o fetched, served and predicted successfully on the CLI.
- [X] Model was predicted using a list of smiles and a single smile 
[eos8c0o_fetch.log](https://github.com/ersilia-os/eos8c0o/files/10495804/eos8c0o_fetch.log)
[eos8c0o_single_predict.csv](https://github.com/ersilia-os/eos8c0o/files/10495800/eos8c0o_single_predict.csv)
[eos8c0o_predict.csv](https://github.com/ersilia-os/eos8c0o/files/10495794/eos8c0o_predict.csv)

## COLAB
- [x]  Model eos8c0o fetched, served and predicted successfully on colab
https://colab.research.google.com/drive/1zaDCJXppmG2eXXxLmakjOY_U8nHdttvH?usp=sharing

**Comment by Femme-js** [comment]
Hi @GemmaTuron !

The model was successfully fetched and served with successful predictions on colab and CLI, both.
https://colab.research.google.com/drive/1RP5WQ6dQ97c9ef7wmqZiLb32IlpqHWiw?usp=sharing
[eos8c0o.log](https://github.com/ersilia-os/eos8c0o/files/10527824/eos8c0o.log)

**Comment by GemmaTuron** [comment]
Great, I'll mark this as completed and the model as ready!
